#!/usr/bin/env bash
# Build a double-clickable "MacBook Battery.app" that launches mac-battery-menubar
# without needing a Terminal window. This is a thin wrapper app (a launcher
# script + Info.plist), not a frozen/self-contained bundle: it still runs the
# Python interpreter and venv you already set up, it just gives you a normal
# Finder/Applications/Login-Items entry point instead of a terminal command.
#
# Usage:
#   ./scripts/make_menubar_app.sh /path/to/venv/bin/python3 [output_dir]
#
# Example (from the repo root, after `python3 -m venv .venv && .venv/bin/pip
# install -e ".[menubar]"`):
#   ./scripts/make_menubar_app.sh "$(pwd)/.venv/bin/python3"
#
# The app is written to ~/Applications/MacBook Battery.app by default.
# Double-click it in Finder, or drag it into System Settings > General >
# Login Items to launch it automatically at login.
set -euo pipefail

PYTHON_BIN="${1:?Usage: $0 /path/to/venv/bin/python3 [output_dir]}"
OUT_DIR="${2:-$HOME/Applications}"
APP="$OUT_DIR/MacBook Battery.app"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "error: '$PYTHON_BIN' is not an executable file" >&2
  exit 1
fi

mkdir -p "$APP/Contents/MacOS"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>MacBook Battery</string>
  <key>CFBundleDisplayName</key><string>MacBook Battery</string>
  <key>CFBundleIdentifier</key><string>com.zeekgeek.macbattery</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSUIElement</key><true/>
  <key>LSMinimumSystemVersion</key><string>10.15</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/launcher" <<SCRIPT
#!/usr/bin/env bash
# Generated by scripts/make_menubar_app.sh — re-run that script to rebuild
# after moving the venv or the repo checkout.
exec "$PYTHON_BIN" -m mac_battery.menubar "\$@"
SCRIPT
chmod +x "$APP/Contents/MacOS/launcher"

echo "Built: $APP"
echo
echo "Next steps:"
echo "  1. Open Finder -> Applications (or ~/Applications) and double-click 'MacBook Battery'."
echo "  2. To launch it automatically at login, open System Settings > General >"
echo "     Login Items, click '+', and add this app."
echo "  3. Gatekeeper may ask for confirmation the first time since the app isn't"
echo "     signed/notarized — that's expected for a locally built app; approve it once."
